services:
  data-service:
    build:
      context: ..
      dockerfile: data-service/Dockerfile
    container_name: data-service
    ports:
      - "8002:8002"
    volumes:
      - data_service_storage:/app/data

  workflow-service:
    build:
      context: ..
      dockerfile: workflow-service/Dockerfile
    container_name: workflow-service
    ports:
      - "8001:8001"
    environment:
      DATA_SERVICE_URL: http://data-service:8002
    depends_on:
      - data-service

  presentation-service:
    build:
      context: ..
      dockerfile: presentation-service/Dockerfile
    container_name: presentation-service
    ports:
      - "8000:8000"
    environment:
      WORKFLOW_SERVICE_URL: http://workflow-service:8001
      DATA_SERVICE_URL: http://data-service:8002
    depends_on:
      - workflow-service
      - data-service

volumes:
  data_service_storage:
