STATUS_APPROVED = "APPROVED"
STATUS_NEEDS_REVISION = "NEEDS REVISION"
STATUS_INCOMPLETE = "INCOMPLETE"

CATEGORY_OPPORTUNITY = "OPPORTUNITY"
CATEGORY_ACADEMIC = "ACADEMIC"
CATEGORY_SOCIAL = "SOCIAL"
CATEGORY_GENERAL = "GENERAL"

PRIORITY_HIGH = "HIGH"
PRIORITY_MEDIUM = "MEDIUM"
PRIORITY_NORMAL = "NORMAL"

PROCESSING_PENDING = "PENDING"
PROCESSING_DONE = "DONE"